# Generated by Django 5.2.6 on 2025-09-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarkedDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("User_Name", models.CharField(default="Unkown User", max_length=30)),
                ("room", models.CharField(default="NA", max_length=10)),
                ("date", models.DateField()),
                ("cleaned", models.BooleanField(default=False)),
            ],
        ),
    ]
